#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-krbV
Version  : 1.0.90
Release  : 2
URL      : http://pypi.debian.net/python-krbV/python-krbV-1.0.90.tar.bz2
Source0  : http://pypi.debian.net/python-krbV/python-krbV-1.0.90.tar.bz2
Summary  : Python extension module for Kerberos 5
Group    : Development/Tools
License  : LGPL-2.1 LGPL-2.1+
Requires: python-krbV-legacypython
BuildRequires : e2fsprogs-dev
BuildRequires : krb5-dev
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
python-krbV allows python programs to use Kerberos 5 authentication and security.

%package legacypython
Summary: legacypython components for the python-krbV package.
Group: Default

%description legacypython
legacypython components for the python-krbV package.


%prep
%setup -q -n python-krbV-1.0.90

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1505058298
python2 setup.py build -b py2

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)
/usr/example/krbV-code-snippets.py
/usr/example/krbV-code-snippets.pyc
/usr/example/krbV-code-snippets.pyo
/usr/test/python-krbV-test.py
/usr/test/python-krbV-test.pyc
/usr/test/python-krbV-test.pyo

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*
