#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-krbV
Version  : 1.0.90
Release  : 1
URL      : https://pypi.python.org/packages/07/46/69342afe17fcc054e285c53b12d0b8eddb24458c2b9d0a340bbb9894ff38/python-krbV-1.0.90.tar.bz2
Source0  : https://pypi.python.org/packages/07/46/69342afe17fcc054e285c53b12d0b8eddb24458c2b9d0a340bbb9894ff38/python-krbV-1.0.90.tar.bz2
Summary  : Python extension module for Kerberos 5
Group    : Development/Tools
License  : LGPL-2.1 LGPL-2.1+
Requires: python-krbV-python
BuildRequires : e2fsprogs-dev
BuildRequires : krb5-dev
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
python-krbV allows python programs to use Kerberos 5 authentication and security.

%package python
Summary: python components for the python-krbV package.
Group: Default
Provides: python-krbv-python

%description python
python components for the python-krbV package.


%prep
%setup -q -n python-krbV-1.0.90

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1499645904
python2 setup.py build -b py2

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)
/usr/example/krbV-code-snippets.py
/usr/example/krbV-code-snippets.pyc
/usr/example/krbV-code-snippets.pyo
/usr/test/python-krbV-test.py
/usr/test/python-krbV-test.pyc
/usr/test/python-krbV-test.pyo

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
